---
title: "Reproducible Research Course Project 1"
author: "tanaya"
output: html_document
---



# Loading and preprocessing the data
if (!file.exists('activity.csv')) {
  unzip(zipfile = "activity.zip")
}
activityData <- read.csv(file="activity.csv", header=TRUE)

# What is mean total number of steps taken per day?
# Calculate the total number of steps taken per day

total_steps_per_day <- sum(activityData$steps, na.rm = TRUE)
print (total_steps_per_day)
## [1] 570608

# Make a histogram of the total number of steps taken per day
total_steps <- aggregate(steps ~ date, activityData, FUN=sum, na.rm = TRUE)

hist(total_steps$steps,
     main = "Total Steps per Day",
     xlab = "Number of Steps")

# Calculate and report the mean and median of total steps taken per day
meansteps <- mean(total_steps$steps, na.rm = TRUE)
medsteps <- median(total_steps$steps, na.rm = TRUE)
print (meansteps)
print (medsteps)
## [1] 10766.19
## [1] 10765

#What is the average daily activity pattern?
# Make a time-series plot of the 5-minute interval and the average number of
# steps taken, averaged across all days.

meanStepsByInt <- aggregate(steps ~ interval, activityData, mean)
plot(x = meanStepsByInt$interval, y = meanStepsByInt$steps, type = "l") 

# Which 5-minute interval across all days contain the maximum number of steps
maxday <- meanStepsByInt[which.max(meanStepsByInt$steps),]
print (maxday)
##[1]     interval    steps
104      835 206.1698

#Imputing missing values 
# Calculate and report the total number of missing values in the dataset

# Calculate and report the total number of missing values in the dataset

total_missingval <- 0
for (i in 1:17568)
{
  if(is.na(activityData$steps[i])) 
    total_missingval <- total_missingval+1 
}
print (total_missingval)

# Devise a strategy for filling in all of the missing values

imp_activityData <- transform(activityData, steps = ifelse(is.na(activityData$steps),
                              meanStepsByInt$steps[match(activityData$interval,                                                                 meanStepsByInt$interval)],
                              activityData$steps))

# Make a histogram of the total number of steps taken each day and
# and report the mean and median.
impStepsByInt <- aggregate(steps ~ date, imp_activityData, FUN=sum, na.rm = TRUE)
hist(impStepsByInt$steps,
     main = "Imputed Number of Steps Per Day",
     xlab = "Number of Steps")

impMeanSteps <- mean(impStepsByInt$steps, na.rm = TRUE)
impMedSteps <- median(impStepsByInt$steps, na.rm = TRUE)
diffMean = impMeanSteps - meanSteps
diffMed = impMedSteps - medSteps
diffTotal = sum(impStepsByInt$steps) - sum(totalSteps$steps)
print(impMeanSteps)
print(impMedSteps)
##[1] 2304
##[1] 10766.19
##[1] 10766.19

# Are there differences in activity patterns between weekdays and weekends?
# Create a new factor variable in the dataset with two levels - "weekend" and "weekday"
Daytype <- function(date) {
  day <- weekdays(date)
  if (day %in% c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'))
    return ("weekeday")
  else if (day %in% c('Saturday', 'Sunday'))
    return ("weekend")
  else
    stop ("Invalid Date Format.")
}
imp_activityData$date <- as.Date(imp_activityData$date)
imp_activityData$day <- sapply(imp_activityData$date, FUN = DayType)

# Make a panel plot containnig a time-series plot of the 5-minute interval
# and the average number of steps taken across all weekdays or weekends
meanStepsByDay <- aggregate(steps ~ interval + day, imp_activityData, mean)
ggplot(data = meanStepsByDay, aes(x = interval, y = steps)) + 
  geom_line() +
  facet_grid(day ~ .) +
  ggtitle("Average Daily Activity Pattern") +
  xlab("5-minute Interval") +
  ylab("Avg Number of Steps") +
  theme(plot.title = element_text(hjust = 0.5))
